<center><img src=https://miro.medium.com/max/765/0*p0FtnloWd4ogMvTQ.png>

• O pacote Numerical Python (NumPy) é fundamental para a computação científica em
Python. Ele possibilita o uso de uma estrutura de dados n-dimensionais chamada de array, que é basicamente um conjunto de elementos com o funcionamento similar a de um vetor
ou matriz;


• Aprender o funcionamento básico do NumPy é o primeiro passo para conhecer todo o enorme
ecossistema de ciência de dados e programação científica em Python;


• Pela convenção da comunidade, o NumPy é reconhecido pela abreviatura np. Isto é, podemos
importá-lo da seguinte maneira:

In [1]:
import numpy as np

# Onde o NumPy é utilizado?


Existem diversas tecnologias na atualidade que se beneficiam da performance do NumPy para cálculos matemáticos.

**Machine Learning**: Durante a construção de modelos de Machine Learning, os algoritmos esperam receber os dados em formato numérico, ou em forma de matriz. A biblioteca NumPy é uma das mais utilizadas nas transformações de dados e pré-processamento durante o pipeline de Machine Learning.

**Visão computacional e inteligência artificial**: Toda imagem é vista pelo computador como um conjunto de pixels, que são traduzidos para matrizes numéricas de acordo com cores, saturação e outras características das imagens. O NumPy apresenta-se como uma excelente ferramenta para esse tipo de aplicação.

**Estatística**: Com o advento do Big Data, a quantidade de dados imensa junto com a aplicabilidade do NumPy para cálculos estatísticos, matemáticos e matriciais tem mostrado todo seu potencial atualmente.

**Engenharias**: O NumPy é utilizado em engenharias pois possui funcionalidades interessantes e aplicáveis para a área em questão, como cálculos complexos, transformadas de fourier, derivadas, integrais.

In [2]:
# Vamos criar uma lista
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

Arrays são o tipo de objeto básico do NumPy. São como listas em Python, que contém valores armazenados em posições.


<center><img src=https://ifrnead.github.io/rubynapratica/assets/images/estrutura-array.png></center>

Um array também pode ser multidimensional, não se limitando apenas à 3D, dimensão máxima que o ser humano consegue compreender.

<center><img src=https://miro.medium.com/max/3184/1*X0Dg7QfSYtWhSAu-afi8-g.png width=750></center>

# Convertendo minha lista em um array Numpy


In [3]:
# Utliza-se a função array
np.array(minha_lista)

array([1, 2, 3])

In [4]:
type(np.array(minha_lista))

numpy.ndarray

In [5]:
# Criando uma matriz array
# Matriz de duas dimensões
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Observa-se as dimensões de um Numpy array através da quantidade de colchetes presentes

In [6]:
# Utlizar o método np.arange para criar um array numpy de dados
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
# Criar array de 0
np.zeros(3)

array([0., 0., 0.])

In [9]:
# Criar  matriz array de 0
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# Criar  matriz array de 1
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# Matriz identidade
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# Linspace -> quantos numeros quero ver igualmente espaçado na minha serie
np.linspace(1,10, 4)

array([ 1.,  4.,  7., 10.])

## **Criar valores aleatórios**

In [13]:
# Valores aleatorios com distribuição uniforme
np.random.rand(5)

array([0.82212375, 0.737095  , 0.09039407, 0.43387026, 0.33121677])

In [14]:
# Valores aleatorios com distribuição uniforme (matriz)
np.random.rand(5,4)

array([[0.81587828, 0.6978778 , 0.95537247, 0.21997703],
       [0.47805042, 0.63826781, 0.20453153, 0.86783366],
       [0.99398057, 0.50249541, 0.31184223, 0.99617466],
       [0.45834816, 0.10924103, 0.34715939, 0.73328028],
       [0.84808052, 0.1356629 , 0.0345845 , 0.92748967]])

In [15]:
# Valores aleatorios com distribuição uniforme (matriz) Três dimensões 
np.random.rand(5,4, 3)

array([[[0.25768762, 0.96602541, 0.09610497],
        [0.96730032, 0.13041722, 0.16045237],
        [0.87929142, 0.55082197, 0.91774831],
        [0.29893596, 0.61229011, 0.27953577]],

       [[0.06710536, 0.71358291, 0.74048483],
        [0.74075783, 0.23928516, 0.33248763],
        [0.07806111, 0.65272573, 0.96185288],
        [0.62343174, 0.65244119, 0.1571707 ]],

       [[0.32370745, 0.89601838, 0.25559777],
        [0.69050233, 0.89301085, 0.27022523],
        [0.15301413, 0.21573654, 0.02305868],
        [0.72003068, 0.56016841, 0.44380193]],

       [[0.47732471, 0.56934499, 0.43497387],
        [0.53819262, 0.46576407, 0.62726406],
        [0.9934398 , 0.56499248, 0.62119704],
        [0.94578447, 0.84871622, 0.43498431]],

       [[0.90972952, 0.9481481 , 0.21586853],
        [0.57052369, 0.09431423, 0.97481883],
        [0.7056574 , 0.8071664 , 0.84668031],
        [0.12068976, 0.0035941 , 0.98696965]]])

In [16]:
# Valores aleatorios com distribuição normal
np.random.randn(5)

array([-0.77606862, -0.09365541,  1.26451762,  0.68498521, -0.25310664])

In [17]:
# Valores aleatorios inteiros
np.random.randint(0,100,10)

array([91,  3, 52,  4, 43,  2, 31, 97, 59, 14])

In [18]:
# Criando um array (vetor) de 25 elementos
arr = np.random.rand(25)
arr

array([0.01991518, 0.38711789, 0.52826312, 0.14104464, 0.23350663,
       0.55595542, 0.79543606, 0.32013219, 0.58575348, 0.61592142,
       0.06602826, 0.82220123, 0.35812662, 0.53593144, 0.18943548,
       0.54279509, 0.86551609, 0.95408549, 0.27401788, 0.60154935,
       0.39356113, 0.04428716, 0.26414826, 0.65274828, 0.84292539])

## **Alterar dimensoes do array**

In [19]:
# Reshape -> função para alterar o as dimensoes do array 
arr = arr.reshape((5,5))
# o elemento agora foi alterado para uma matriz 5 x 5
arr

array([[0.01991518, 0.38711789, 0.52826312, 0.14104464, 0.23350663],
       [0.55595542, 0.79543606, 0.32013219, 0.58575348, 0.61592142],
       [0.06602826, 0.82220123, 0.35812662, 0.53593144, 0.18943548],
       [0.54279509, 0.86551609, 0.95408549, 0.27401788, 0.60154935],
       [0.39356113, 0.04428716, 0.26414826, 0.65274828, 0.84292539]])

In [20]:
# Verificar as dimensoes do meu array
arr.shape

(5, 5)

## **Funções algébricas do Numpy**

In [21]:
# Verificar o maior valor do array
arr.max()

0.9540854943647609

In [22]:
# Verificar o menor valor do array
arr.min()

0.019915177736993805

In [23]:
# Verificar a média do array
arr.mean()

0.46361612747214065

In [24]:
arr

array([[0.01991518, 0.38711789, 0.52826312, 0.14104464, 0.23350663],
       [0.55595542, 0.79543606, 0.32013219, 0.58575348, 0.61592142],
       [0.06602826, 0.82220123, 0.35812662, 0.53593144, 0.18943548],
       [0.54279509, 0.86551609, 0.95408549, 0.27401788, 0.60154935],
       [0.39356113, 0.04428716, 0.26414826, 0.65274828, 0.84292539]])

In [25]:
# Retornar o indice no qual o maior elemento se encontra
arr.argmax()

17

In [26]:
# Retornar o indice no qual o menor elemento se encontra
arr.argmin()

0

## **Indexação e fatiamento de Arrays**

<center><img src=https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png width=750></center>


Fonte: Documentação NumPy/Scipy

<center><img src=https://www.oreilly.com/library/view/python-for-data/9781491957653/assets/pyda_0402.png width=400></center> 

Resumo sobre indexação.
Percebam que os dois-pontos **``:``** separam os índices iniciais e finais de uma dimensão ou eixo, enquanto que a **``,``** separa as dimensões ou eixos.

    arr[indice_inicial_dim0:indice_final_dim0, indice_inicial_dim1:indice_final_dim1, ...]

### **Array Unidimensional**

In [27]:
# Criar um array de dados 
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [28]:
# Buscar valores do array por indices
# A contagem dos indices iniciam a partir do 0
arr[0] # primeiro indice
arr[1] # segundo indice
arr[4] # quinto indice

12

In [29]:
# Puxando multiplos elementos
arr[2:] # a partir do segundo indice até o final
arr[2:5] # a partir do segundo indice até o quarto
arr[:] # todos os elementos
arr[:5] # desde o inicio até o quarto indice

array([ 0,  3,  6,  9, 12])

### **Array bidimensional**

In [30]:
arr = np.arange(50).reshape((5,10))

In [31]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [32]:
arr.shape

(5, 10)

In [33]:
arr2 = arr[:3]
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
arr[0:2,0:6] # (linha,coluna)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15]])

## Array tridimensional

In [36]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [37]:
arr.shape

(2, 2, 4)

In [38]:
# Manipulando array com 3 dimensoes
arr[1][0]

array([ 8,  9, 10, 11])

## **Operação com vetores e arrays numpy** 

In [39]:
# Criando um numpy array
arr = np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
# Soma de arrays
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [41]:
# Subtração de arrays
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
# Multiplicação de arrays
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [43]:
# Divisão de arrays
arr/arr

C:\Users\Luiz\Anaconda3\envs\maps\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [44]:
## Exponenciação de arrays
arr **3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375], dtype=int32)

In [45]:
# Operações com escalares
arr + 273.15
arr - 100
arr * 100
arr /100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15])

In [46]:
# Raiz quadrada de arrays
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [47]:
# Media de arrays
np.mean(arr)

7.5

In [48]:
# Desvio padrão de arrays
np.std(arr)

4.6097722286464435

In [49]:
# Outra forma de ver o maximo e o minimo dos arrays
np.max(arr)
np.min(arr)

0

Especificar axis em alguns parametros 

axis = 0 -> significa a operação matematica nas linhas

axis = 1 -> significa a opeção matematica nas colunas

In [50]:
arr
#arr.astype('int')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
minha_lista = [1.5,5.2,1.7,9.7]
minha_lista = np.array(minha_lista)

In [52]:
minha_lista

array([1.5, 5.2, 1.7, 9.7])

In [53]:
# Verificar o tipo de variavel 
minha_lista.dtype

dtype('float64')

In [54]:
# Método para alterar formato da variavel 
# float64 para int
minha_lista.astype('int')

array([1, 5, 1, 9])

In [55]:
# Podemos transformar qualquer tipo de dado, sabendo que...
arr = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])

# ... quando transformamos de float para int... 
arr.astype(np.int32)

# ... as casas decimais serão simplesmente ignoradas! E não se trata de arredondamento, e sim
# truncamento! As casa decimais serão ELIMINADAS! Atente-se!
arr.astype(np.int32)

array([ 1,  3, -5,  9,  4])

Podemos alterar entre formatos não-numéricos também.

In [56]:
# Vamos criar um array com string que representam números...
numeric_str = np.array(['1', '2', '3', '4'])

# ... e agora transformá-lo para o tipo de dado desejado
numeric_str.astype(float)

array([1., 2., 3., 4.])

### Filtrar ou Atribuir valores diante de determinadas condições (booleanos e arrays) 

In [57]:
# Criando um array 
numeros = np.random.randn(7, 4)

In [58]:
numeros

array([[ 0.24163389, -0.23243331,  0.06638442, -0.94194753],
       [-0.53898343,  1.57487942, -0.19037591,  2.9158519 ],
       [ 1.23165632, -0.20456682, -0.21023797,  0.39836398],
       [-0.09777964, -0.29446222,  0.89383311, -0.2492154 ],
       [ 0.01231812, -0.69914615, -0.1077351 ,  1.31283985],
       [-0.81360825,  0.51229788, -0.67158437, -1.21916914],
       [-1.24083179, -1.69944975,  0.38682   , -0.15919375]])

* **Podemos combinar os numpy arrays com os operados de comparação**

In [59]:
numeros > 0.2

array([[ True, False, False, False],
       [False,  True, False,  True],
       [ True, False, False,  True],
       [False, False,  True, False],
       [False, False, False,  True],
       [False,  True, False, False],
       [False, False,  True, False]])

Podemos inverter um array booleano ou negar uma condição com o símbolo **``~``** .

In [60]:
~(numeros > 0.2)

array([[False,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True,  True, False],
       [ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True, False,  True,  True],
       [ True,  True, False,  True]])

In [61]:
numeros != 0 

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

* **Para associarmos várias condições, podemos utilizar os operadores aritméticos booleanos **``&``** (E) e **``|``** (OU).**

In [62]:
((numeros > 0.5) & (numeros < 1.5))

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False,  True, False, False],
       [False, False, False, False]])

In [63]:
# Para substituirmos todos os valores de um array menores que zero por zero
numeros[numeros < 0] = 0
numeros

array([[0.24163389, 0.        , 0.06638442, 0.        ],
       [0.        , 1.57487942, 0.        , 2.9158519 ],
       [1.23165632, 0.        , 0.        , 0.39836398],
       [0.        , 0.        , 0.89383311, 0.        ],
       [0.01231812, 0.        , 0.        , 1.31283985],
       [0.        , 0.51229788, 0.        , 0.        ],
       [0.        , 0.        , 0.38682   , 0.        ]])

In [64]:
# Exemplo de uso para o operador & para duas ou mais condicoes
numeros[(numeros < 0.5) & (numeros > 0.1)] = 5
numeros 

array([[5.        , 0.        , 0.06638442, 0.        ],
       [0.        , 1.57487942, 0.        , 2.9158519 ],
       [1.23165632, 0.        , 0.        , 5.        ],
       [0.        , 0.        , 0.89383311, 0.        ],
       [0.01231812, 0.        , 0.        , 1.31283985],
       [0.        , 0.51229788, 0.        , 0.        ],
       [0.        , 0.        , 5.        , 0.        ]])

## Expressões lógicas condicionais com arrays

In [65]:
arr = np.random.randn(4, 4)
arr

array([[ 0.05558176,  0.06911294,  0.21364669, -0.36229423],
       [-0.47728409,  1.74326769, -0.81326552, -0.04877153],
       [-1.08000015,  0.70756687,  0.4433576 , -0.05520615],
       [ 0.66481297, -0.48667879, -0.71193874, -0.43683843]])

In [66]:
# Vamos criar um array booleano para usar como nossa condição
arr > 0

array([[ True,  True,  True, False],
       [False,  True, False, False],
       [False,  True,  True, False],
       [ True, False, False, False]])

In [67]:
# Aqui, onde a condição for satisfeita, substituímos o valor por 1, caso não for satisfeita, inserimos -1
np.where(arr > 0, 1, -1)

array([[ 1,  1,  1, -1],
       [-1,  1, -1, -1],
       [-1,  1,  1, -1],
       [ 1, -1, -1, -1]])

In [68]:
# Neste outro exemplo, vamos substituir os valores positivos por 10 e manter os valores negativos
np.where(arr > 0, 10, arr)

array([[10.        , 10.        , 10.        , -0.36229423],
       [-0.47728409, 10.        , -0.81326552, -0.04877153],
       [-1.08000015, 10.        , 10.        , -0.05520615],
       [10.        , -0.48667879, -0.71193874, -0.43683843]])

## Dicas
Para mais dicas e modo de uso do numpy acesse: https://acervolima.com/python-numpy-exercicios-praticos-perguntas-e-solucoes/